### ISSUE TITLE
would love emoji shortcodes to work

### ISSUE THREAD

**Issue by jeremy-allen** [christopherkenny/bskyr#11]
Having a ton of fun with bskyr on Bluesky today! 

I would love for this to work, but it does not:

```
msg <- ":fire:"
  
bs_post(text = msg)
```

The unicode works, but is less fun:

```
msg <- "the unicode works: \U0001F525"
```

**Comment by christopherkenny** [comment]
This seemed high on the simple-to-implement by usefulness axes, so I've just pushed a simple version of it. Right now, it operates entirely on [the emoji pacakge](https://emilhvitfeldt.github.io/emoji/)'s `emoji::emoji_names`, which gives pretty broad support for emojis within R. I may add support for the emoji keywords, but I am a bit hesitant as it removes the one-name-to-one-emoji relationship.

**Comment by jeremy-allen** [comment]
Thank you!
